import puppeteer from 'puppeteer-core';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url));
const profile=path.join(root,'chrome-profile');
const browser=await puppeteer.launch({executablePath:'/usr/bin/google-chrome',userDataDir:profile,headless:true,pipe:true,enableExtensions:true,args:['--enable-unsafe-extension-debugging','--remote-debugging-port=0']});
await browser.installExtension(path.join(root,'host-extension'));
const worker=await browser.waitForTarget(t=>t.type()==='service_worker',{timeout:15000});
const session=await worker.createCDPSession();
await session.send('Runtime.enable');
session.on('Runtime.consoleAPICalled',event=>console.log('Proxy:',event.args.map(a=>a.value||a.description).join(' ')));
session.on('Runtime.exceptionThrown',event=>console.error('Proxy error:',event.exceptionDetails.text,event.exceptionDetails.exception?.description));
const page=await browser.newPage();
await page.goto('https://demo.yubico.com/webauthn-technical',{waitUntil:'domcontentloaded'});
const [port,wsPath]=(await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).trim().split('\n');
await fs.writeFile(path.join(root,'host-state.json'),JSON.stringify({endpoint:'ws://127.0.0.1:'+port+wsPath}),{mode:0o600});
console.log('Isolated procbox Yubico test ready');
process.on('SIGTERM',async()=>{await browser.close();process.exit();});
process.on('SIGINT',async()=>{await browser.close();process.exit();});
