// Uses a virtual authenticator ONLY on an isolated QA origin/state directory.
import assert from 'node:assert/strict';
import puppeteer from 'puppeteer-core';
const port=8796, origin='http://localhost:'+port, fixture='http://127.0.0.1:'+port;
const browser=await puppeteer.launch({executablePath:process.env.SHARED_BROWSER_CHROME,headless:true,args:['--disable-dev-shm-usage']});
let checks=0;const pass=label=>{checks++;console.log('PASS '+label);};
const wait=async fn=>{for(let i=0;i<100;i++){const x=await fn();if(x)return x;await new Promise(r=>setTimeout(r,80));}throw Error('Expected state did not arrive');};
try{
 const phone=await browser.newPage();await phone.setExtraHTTPHeaders({'Tailscale-User-Login':'manbir@asgroup.ai'});
 const cdp=await phone.createCDPSession();await cdp.send('WebAuthn.enable');
 const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 await phone.goto(origin+'/passkey/');
 const api=(path,data)=>phone.evaluate(async({path,data})=>{
   const r=await fetch('/passkey/api/'+path,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
   return {status:r.status,body:await r.json()};
 },{path,data});
 assert.equal((await api('state')).body.registered,false);
 await phone.click('#register');await wait(async()=> (await api('state')).body.registered);
 pass('real WebAuthn registration verified with isolated virtual authenticator');
 assert.equal((await api('register/options',{})).status,400);
 pass('enrolled credential cannot be silently replaced');
 const site=await browser.newPage();await site.goto(fixture+'/fixture');
 const siteAPI=(path,post=false)=>site.evaluate(async({path,post})=>{const r=await fetch('/fixture/'+path,post?{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}:{});return {status:r.status,body:await r.json()};},{path,post});
 assert.equal((await siteAPI('workspace')).status,401);
 let request=(await siteAPI('login',true)).body.request;
 assert.equal((await siteAPI('workspace')).status,401);
 pass('requesting sign-in does not unlock protected endpoint');
 const assertion=async(optionsJSON)=>phone.evaluate(async options=>{
   const credential=await navigator.credentials.get({publicKey:PublicKeyCredential.parseRequestOptionsFromJSON(options)});
   return credential.toJSON();
 },optionsJSON);
 let options=(await api('auth/options',{id:request.id})).body;
 let response=await assertion(options);
 response.response.signature=Buffer.from('invalid-signature').toString('base64url');
 assert.equal((await api('auth/verify',{id:request.id,response})).status,400);
 assert.equal((await siteAPI('workspace')).status,401);
 pass('invalid signature cannot authenticate the agent');
 options=(await api('auth/options',{id:request.id})).body;response=await assertion(options);
 const clientData=JSON.parse(Buffer.from(response.response.clientDataJSON,'base64url').toString());clientData.origin='https://other.example';response.response.clientDataJSON=Buffer.from(JSON.stringify(clientData)).toString('base64url');
 assert.equal((await api('auth/verify',{id:request.id,response})).status,400);
 pass('wrong origin rejected');
 options=(await api('auth/options',{id:request.id})).body;
 await cdp.send('WebAuthn.setUserVerified',{authenticatorId,isUserVerified:false});
 response=await assertion({...options,userVerification:'discouraged'});
 assert.equal((await api('auth/verify',{id:request.id,response})).status,400);
 assert.equal((await siteAPI('workspace')).status,401);
 await cdp.send('WebAuthn.setUserVerified',{authenticatorId,isUserVerified:true});
 pass('valid authenticator response without user verification rejected');
 options=(await api('auth/options',{id:request.id})).body;response=await assertion(options);
 await api('cancel',{id:request.id});
 assert.equal((await api('auth/verify',{id:request.id,response})).status,400);
 assert.equal((await siteAPI('workspace')).status,401);
 pass('canceled request rejects even a signed late response');
 request=(await siteAPI('login',true)).body.request;
 options=(await api('auth/options',{id:request.id})).body;response=await assertion(options);
 const second=await browser.createBrowserContext(), other=await second.newPage();await other.goto(fixture+'/fixture');
 const otherRequest=await other.evaluate(async()=>{const r=await fetch('/fixture/login',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});return (await r.json()).request;});
 await api('auth/options',{id:otherRequest.id});
 assert.equal((await api('auth/verify',{id:otherRequest.id,response})).status,400);
 assert.equal((await api('auth/verify',{id:request.id,response})).status,200);
 assert.equal((await api('auth/verify',{id:request.id,response})).status,400);
 await wait(async()=> (await siteAPI('status')).body.authenticated);
 assert.equal((await siteAPI('workspace')).status,200);
 assert.equal(await other.evaluate(async()=> (await fetch('/fixture/workspace')).status),401);
 pass('approval binds to original request/session, unlocks once, and rejects replay');
 await second.close();
 const unauthorized=await fetch(origin+'/passkey/api/state');assert.equal(unauthorized.status,403);
 const badOrigin=await fetch(origin+'/passkey/api/auth/options',{method:'POST',headers:{'Tailscale-User-Login':'manbir@asgroup.ai',Origin:'https://other.example','Content-Type':'application/json'},body:'{}'});assert.equal(badOrigin.status,403);
 pass('approval endpoints require owner identity and exact request origin');
 await site.bringToFront();await siteAPI('logout',true);request=(await siteAPI('login',true)).body.request;
 await phone.bringToFront();
 await phone.waitForSelector('[data-request="'+request.id+'"] button');
 await phone.click('[data-request="'+request.id+'"] button');
 await wait(async()=> (await siteAPI('status')).body.authenticated);
 assert.equal((await siteAPI('workspace')).status,200);
 pass('phone approval button completes native WebAuthn and unlocks the remote site');
 console.log(`${checks} passkey integration checks passed`);
}finally{await browser.close();}
